apiVersion: apps/v1
kind: Deployment
metadata:
  name: top-cat-ui-deployment
spec:
  replicas: 1 # Change the number for scaling
  selector:
    matchLabels:
      app: top-cat-ui
  template:
    metadata:
      labels:
        app: top-cat-ui
    spec:
      # hostNetwork: true
      # dnsPolicy: ClusterFirstWithHostNet
      # imagePullSecrets:
      #   - name: docker-registry-secret
      containers:
        - name: top-cat-ui
          image: calumd94/top-cat-ui:latest
          ports:
            - containerPort: 80 # or whatever port your app listens on
          env:
            - name: ENV
              value: "prod"
