apiVersion: v1
kind: Service
metadata:
  name: top-cat-ui-service
spec:
  selector:
    app: top-cat-ui
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32325
